# Voting Classifier

In [17]:
from sklearn.datasets import load_iris
iris = load_iris()
X = iris.data[:,1:3]
y = iris.target

In [22]:
y

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2])

In [20]:
iris

{'data': array([[5.1, 3.5, 1.4, 0.2],
        [4.9, 3. , 1.4, 0.2],
        [4.7, 3.2, 1.3, 0.2],
        [4.6, 3.1, 1.5, 0.2],
        [5. , 3.6, 1.4, 0.2],
        [5.4, 3.9, 1.7, 0.4],
        [4.6, 3.4, 1.4, 0.3],
        [5. , 3.4, 1.5, 0.2],
        [4.4, 2.9, 1.4, 0.2],
        [4.9, 3.1, 1.5, 0.1],
        [5.4, 3.7, 1.5, 0.2],
        [4.8, 3.4, 1.6, 0.2],
        [4.8, 3. , 1.4, 0.1],
        [4.3, 3. , 1.1, 0.1],
        [5.8, 4. , 1.2, 0.2],
        [5.7, 4.4, 1.5, 0.4],
        [5.4, 3.9, 1.3, 0.4],
        [5.1, 3.5, 1.4, 0.3],
        [5.7, 3.8, 1.7, 0.3],
        [5.1, 3.8, 1.5, 0.3],
        [5.4, 3.4, 1.7, 0.2],
        [5.1, 3.7, 1.5, 0.4],
        [4.6, 3.6, 1. , 0.2],
        [5.1, 3.3, 1.7, 0.5],
        [4.8, 3.4, 1.9, 0.2],
        [5. , 3. , 1.6, 0.2],
        [5. , 3.4, 1.6, 0.4],
        [5.2, 3.5, 1.5, 0.2],
        [5.2, 3.4, 1.4, 0.2],
        [4.7, 3.2, 1.6, 0.2],
        [4.8, 3.1, 1.6, 0.2],
        [5.4, 3.4, 1.5, 0.4],
        [5.2, 4.1, 1.5, 0.1],
        [5.5, 4.2, 1.4, 0.2],
        [4.9, 3.1, 1.5, 0.2],
        [5. , 3.2, 1.2, 0.2],
        [5.5, 3.5, 1.3, 0.2],
        [4.9, 3.6, 1.4, 0.1],
        [4.4, 3. , 1.3, 0.2],
        [5.1, 3.4, 1.5, 0.2],
        [5. , 3.5, 1.3, 0.3],
        [4.5, 2.3, 1.3, 0.3],
        [4.4, 3.2, 1.3, 0.2],
        [5. , 3.5, 1.6, 0.6],
        [5.1, 3.8, 1.9, 0.4],
        [4.8, 3. , 1.4, 0.3],
        [5.1, 3.8, 1.6, 0.2],
        [4.6, 3.2, 1.4, 0.2],
        [5.3, 3.7, 1.5, 0.2],
        [5. , 3.3, 1.4, 0.2],
        [7. , 3.2, 4.7, 1.4],
        [6.4, 3.2, 4.5, 1.5],
        [6.9, 3.1, 4.9, 1.5],
        [5.5, 2.3, 4. , 1.3],
        [6.5, 2.8, 4.6, 1.5],
        [5.7, 2.8, 4.5, 1.3],
        [6.3, 3.3, 4.7, 1.6],
        [4.9, 2.4, 3.3, 1. ],
        [6.6, 2.9, 4.6, 1.3],
        [5.2, 2.7, 3.9, 1.4],
        [5. , 2. , 3.5, 1. ],
        [5.9, 3. , 4.2, 1.5],
        [6. , 2.2, 4. , 1. ],
        [6.1, 2.9, 4.7, 1.4],
        [5.6, 2.9, 3.6, 1.3],
        [6.7, 3.1, 4.4, 1.4],
        [5.6, 3. , 4.5, 1.5],
        [5.8, 2.7, 4.1, 1. ],
        [6.2, 2.2, 4.5, 1.5],
        [5.6, 2.5, 3.9, 1.1],
        [5.9, 3.2, 4.8, 1.8],
        [6.1, 2.8, 4. , 1.3],
        [6.3, 2.5, 4.9, 1.5],
        [6.1, 2.8, 4.7, 1.2],
        [6.4, 2.9, 4.3, 1.3],
        [6.6, 3. , 4.4, 1.4],
        [6.8, 2.8, 4.8, 1.4],
        [6.7, 3. , 5. , 1.7],
        [6. , 2.9, 4.5, 1.5],
        [5.7, 2.6, 3.5, 1. ],
        [5.5, 2.4, 3.8, 1.1],
        [5.5, 2.4, 3.7, 1. ],
        [5.8, 2.7, 3.9, 1.2],
        [6. , 2.7, 5.1, 1.6],
        [5.4, 3. , 4.5, 1.5],
        [6. , 3.4, 4.5, 1.6],
        [6.7, 3.1, 4.7, 1.5],
        [6.3, 2.3, 4.4, 1.3],
        [5.6, 3. , 4.1, 1.3],
        [5.5, 2.5, 4. , 1.3],
        [5.5, 2.6, 4.4, 1.2],
        [6.1, 3. , 4.6, 1.4],
        [5.8, 2.6, 4. , 1.2],
        [5. , 2.3, 3.3, 1. ],
        [5.6, 2.7, 4.2, 1.3],
        [5.7, 3. , 4.2, 1.2],
        [5.7, 2.9, 4.2, 1.3],
        [6.2, 2.9, 4.3, 1.3],
        [5.1, 2.5, 3. , 1.1],
        [5.7, 2.8, 4.1, 1.3],
        [6.3, 3.3, 6. , 2.5],
        [5.8, 2.7, 5.1, 1.9],
        [7.1, 3. , 5.9, 2.1],
        [6.3, 2.9, 5.6, 1.8],
        [6.5, 3. , 5.8, 2.2],
        [7.6, 3. , 6.6, 2.1],
        [4.9, 2.5, 4.5, 1.7],
        [7.3, 2.9, 6.3, 1.8],
        [6.7, 2.5, 5.8, 1.8],
        [7.2, 3.6, 6.1, 2.5],
        [6.5, 3.2, 5.1, 2. ],
        [6.4, 2.7, 5.3, 1.9],
        [6.8, 3. , 5.5, 2.1],
        [5.7, 2.5, 5. , 2. ],
        [5.8, 2.8, 5.1, 2.4],
        [6.4, 3.2, 5.3, 2.3],
        [6.5, 3. , 5.5, 1.8],
        [7.7, 3.8, 6.7, 2.2],
        [7.7, 2.6, 6.9, 2.3],
        [6. , 2.2, 5. , 1.5],
        [6.9, 3.2, 5.7, 2.3],
        [5.6, 2.8, 4.9, 2. ],
        [7.7, 2.8, 6.7, 2. ],
        [6.3, 2.7, 4.9, 1.8],
        [6.7, 3.3, 5.7, 2.1],
        [7.2, 3.2, 6. , 1.8],
        [6.2, 2.8, 4.8, 1.8],
        [6.1, 3. , 4.9, 1.8],
        [6.4, 2.8, 5.6, 2.1],
        [7.2, 3. , 5.8, 1.6],
        [7.4, 2.8, 6.1, 1.9],
        [7.9, 3.8, 6.4, 2. ],
        [6.4, 2.8, 5.6, 2.2],
        [6.3, 2.8, 5.1, 1.5],
        [6.1, 2.6, 5.6, 1.4],
        [7.7, 3. , 6.1, 2.3],
        [6.3, 3.4, 5.6, 2.4],
        [6.4, 3.1, 5.5, 1.8],
        [6. , 3. , 4.8, 1.8],
        [6.9, 3.1, 5.4, 2.1],
        [6.7, 3.1, 5.6, 2.4],
        [6.9, 3.1, 5.1, 2.3],
        [5.8, 2.7, 5.1, 1.9],
        [6.8, 3.2, 5.9, 2.3],
        [6.7, 3.3, 5.7, 2.5],
        [6.7, 3. , 5.2, 2.3],
        [6.3, 2.5, 5. , 1.9],
        [6.5, 3. , 5.2, 2. ],
        [6.2, 3.4, 5.4, 2.3],
        [5.9, 3. , 5.1, 1.8]]),
 'target': array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
        1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
        1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
        2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
        2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2]),
 'target_names': array(['setosa', 'versicolor', 'virginica'], dtype='<U10'),
 'DESCR': '.. _iris_dataset:\n\nIris plants dataset\n--------------------\n\n**Data Set Characteristics:**\n\n    :Number of Instances: 150 (50 in each of three classes)\n    :Number of Attributes: 4 numeric, predictive attributes and the class\n    :Attribute Information:\n        - sepal length in cm\n        - sepal width in cm\n        - petal length in cm\n        - petal width in cm\n        - class:\n                - Iris-Setosa\n                - Iris-Versicolour\n                - Iris-Virginica\n                \n    :Summary Statistics:\n\n    ============== ==== ==== ======= ===== ====================\n                    Min  Max   Mean    SD   Class Correlation\n    ============== ==== ==== ======= ===== ====================\n    sepal length:   4.3  7.9   5.84   0.83    0.7826\n    sepal width:    2.0  4.4   3.05   0.43   -0.4194\n    petal length:   1.0  6.9   3.76   1.76    0.9490  (high!)\n    petal width:    0.1  2.5   1.20   0.76    0.9565  (high!)\n    ============== ==== ==== ======= ===== ====================\n\n    :Missing Attribute Values: None\n    :Class Distribution: 33.3% for each of 3 classes.\n    :Creator: R.A. Fisher\n    :Donor: Michael Marshall (MARSHALL%PLU@io.arc.nasa.gov)\n    :Date: July, 1988\n\nThe famous Iris database, first used by Sir R.A. Fisher. The dataset is taken\nfrom Fisher\'s paper. Note that it\'s the same as in R, but not as in the UCI\nMachine Learning Repository, which has two wrong data points.\n\nThis is perhaps the best known database to be found in the\npattern recognition literature.  Fisher\'s paper is a classic in the field and\nis referenced frequently to this day.  (See Duda & Hart, for example.)  The\ndata set contains 3 classes of 50 instances each, where each class refers to a\ntype of iris plant.  One class is linearly separable from the other 2; the\nlatter are NOT linearly separable from each other.\n\n.. topic:: References\n\n   - Fisher, R.A. "The use of multiple measurements in taxonomic problems"\n     Annual Eugenics, 7, Part II, 179-188 (1936); also in "Contributions to\n     Mathematical Statistics" (John Wiley, NY, 1950).\n   - Duda, R.O., & Hart, P.E. (1973) Pattern Classification and Scene Analysis.\n     (Q327.D83) John Wiley & Sons.  ISBN 0-471-22361-1.  See page 218.\n   - Dasarathy, B.V. (1980) "Nosing Around the Neighborhood: A New System\n     Structure and Classification Rule for Recognition in Partially Exposed\n     Environments".  IEEE Transactions on Pattern Analysis and Machine\n     Intelligence, Vol. PAMI-2, No. 1, 67-71.\n   - Gates, G.W. (1972) "The Reduced Nearest Neighbor Rule".  IEEE Transactions\n     on Information Theory, May 1972, 431-433.\n   - See also: 1988 MLC Proceedings, 54-64.  Cheeseman et al"s AUTOCLASS II\n     conceptual clustering system finds 3 classes in the data.\n   - Many, many more ...',
 'feature_names': ['sepal length (cm)',
  'sepal width (cm)',
  'petal length (cm)',
  'petal width (cm)'],
 'filename': 'C:\\ProgramData\\Anaconda3\\lib\\site-packages\\sklearn\\datasets\\data\\iris.csv'}

In [23]:
#split the dataset into training and testing data
from sklearn.model_selection import train_test_split
X_train,X_test,y_train,y_test = train_test_split(X,y,test_size= 0.30,
                                                 random_state = 0)

In [24]:
from sklearn.linear_model import LogisticRegression
from sklearn.ensemble import RandomForestClassifier
from sklearn.naive_bayes import GaussianNB
from sklearn.ensemble import VotingClassifier

In [25]:
log_clf = LogisticRegression()
rnd_clf = RandomForestClassifier()
gnb_clf = GaussianNB()

In [33]:
voting_clf = VotingClassifier(estimators=[('lr',log_clf),('rf',rnd_clf),
                                          ('gb',gnb_clf)],
                              voting = 'soft')
voting_clf.fit(X_train,y_train)

C:\ProgramData\Anaconda3\lib\site-packages\sklearn\linear_model\logistic.py:433: FutureWarning: Default solver will be changed to 'lbfgs' in 0.22. Specify a solver to silence this warning.
  FutureWarning)
C:\ProgramData\Anaconda3\lib\site-packages\sklearn\linear_model\logistic.py:460: FutureWarning: Default multi_class will be changed to 'auto' in 0.22. Specify the multi_class option to silence this warning.
  "this warning.", FutureWarning)

VotingClassifier(estimators=[('lr', LogisticRegression(C=1.0, class_weight=None, dual=False, fit_intercept=True,
          intercept_scaling=1, max_iter=100, multi_class='warn',
          n_jobs=None, penalty='l2', random_state=None, solver='warn',
          tol=0.0001, verbose=0, warm_start=False)), ('rf', RandomFo...ne, verbose=0,
            warm_start=False)), ('gb', GaussianNB(priors=None, var_smoothing=1e-09))],
         flatten_transform=None, n_jobs=None, voting='soft', weights=None)

In [35]:
from sklearn.metrics import accuracy_score
for clf in (log_clf,rnd_clf,gnb_clf):
    clf.fit(X_train,y_train)
    y_pred = clf.predict(X_test)
    print(clf.__class__.__name__,accuracy_score(y_test,y_pred))
print(voting_clf.__class__.__name__,accuracy_score(y_test,y_pred))

LogisticRegression 0.7555555555555555
RandomForestClassifier 0.9333333333333333
GaussianNB 0.9555555555555556
VotingClassifier 0.9555555555555556

C:\ProgramData\Anaconda3\lib\site-packages\sklearn\linear_model\logistic.py:433: FutureWarning: Default solver will be changed to 'lbfgs' in 0.22. Specify a solver to silence this warning.
  FutureWarning)
C:\ProgramData\Anaconda3\lib\site-packages\sklearn\linear_model\logistic.py:460: FutureWarning: Default multi_class will be changed to 'auto' in 0.22. Specify the multi_class option to silence this warning.
  "this warning.", FutureWarning)

Ensemble models work best when the predictors are as independent from one another as possible.One way to get diverse classifes is to train them using very different algorithms.This increases 
the chances that they will make very differnet types of errors,improving the 
ensemble's accuracy.

Thus the voting classifier slighltly outperforms all the individual classifiers,if all the classifiers are able to estimate the class probabilities (they have predict_proba() method)then we can predict the class with the highest class probability,averaged all over the individual classifiers,this is called "SoftVoting".It oftens achieves higher performance than hardvoting because it gives more weigh to highly confident votes

One way to get a diverse set of classifiers is to use very different training algorithms as just discussed.Another approach is to use the same training algorithm for every predictor,but to train them on different random subsets of the training set.When the sampling is performed with replacement,this method is called "Bagging" [Bootstrap Aggregating] When sampling is performd without replacement,it is called as "Pasting".Thus bagging and pasting allows training instances to be sampled several times for the same predictor.

In [36]:
import pandas as pd
pima= pd.read_csv("diabetes.csv")
pima

,Pregnancies,Glucose,BloodPressure,SkinThickness,Insulin,BMI,DiabetesPedigreeFunction,Age,Outcome
0,6,148,72,35,0,33.6,0.627,50,1
1,1,85,66,29,0,26.6,0.351,31,0
2,8,183,64,0,0,23.3,0.672,32,1
3,1,89,66,23,94,28.1,0.167,21,0
4,0,137,40,35,168,43.1,2.288,33,1
5,5,116,74,0,0,25.6,0.201,30,0
6,3,78,50,32,88,31.0,0.248,26,1
7,10,115,0,0,0,35.3,0.134,29,0
8,2,197,70,45,543,30.5,0.158,53,1
9,8,125,96,0,0,0.0,0.232,54,1
10,4,110,92,0,0,37.6,0.191,30,0
11,10,168,74,0,0,38.0,0.537,34,1
12,10,139,80,0,0,27.1,1.441,57,0
13,1,189,60,23,846,30.1,0.398,59,1
14,5,166,72,19,175,25.8,0.587,51,1
15,7,100,0,0,0,30.0,0.484,32,1
16,0,118,84,47,230,45.8,0.551,31,1
17,7,107,74,0,0,29.6,0.254,31,1
18,1,103,30,38,83,43.3,0.183,33,0
19,1,115,70,30,96,34.6,0.529,32,1
20,3,126,88,41,235,39.3,0.704,27,0
21,8,99,84,0,0,35.4,0.388,50,0
22,7,196,90,0,0,39.8,0.451,41,1
23,9,119,80,35,0,29.0,0.263,29,1
24,11,143,94,33,146,36.6,0.254,51,1
25,10,125,70,26,115,31.1,0.205,41,1
26,7,147,76,0,0,39.4,0.257,43,1
27,1,97,66,15,140,23.2,0.487,22,0
28,13,145,82,19,110,22.2,0.245,57,0
29,5,117,92,0,0,34.1,0.337,38,0
...,...,...,...,...,...,...,...,...,...
738,2,99,60,17,160,36.6,0.453,21,0
739,1,102,74,0,0,39.5,0.293,42,1
740,11,120,80,37,150,42.3,0.785,48,1
741,3,102,44,20,94,30.8,0.400,26,0
742,1,109,58,18,116,28.5,0.219,22,0
743,9,140,94,0,0,32.7,0.734,45,1
744,13,153,88,37,140,40.6,1.174,39,0
745,12,100,84,33,105,30.0,0.488,46,0
746,1,147,94,41,0,49.3,0.358,27,1
747,1,81,74,41,57,46.3,1.096,32,0
748,3,187,70,22,200,36.4,0.408,36,1
749,6,162,62,0,0,24.3,0.178,50,1
750,4,136,70,0,0,31.2,1.182,22,1
751,1,121,78,39,74,39.0,0.261,28,0
752,3,108,62,24,0,26.0,0.223,25,0
753,0,181,88,44,510,43.3,0.222,26,1
754,8,154,78,32,0,32.4,0.443,45,1
755,1,128,88,39,110,36.5,1.057,37,1
756,7,137,90,41,0,32.0,0.391,39,0
757,0,123,72,0,0,36.3,0.258,52,1
758,1,106,76,0,0,37.5,0.197,26,0
759,6,190,92,0,0,35.5,0.278,66,1
760,2,88,58,26,16,28.4,0.766,22,0
761,9,170,74,31,0,44.0,0.403,43,1
762,9,89,62,0,0,22.5,0.142,33,0
763,10,101,76,48,180,32.9,0.171,63,0
764,2,122,70,27,0,36.8,0.340,27,0
765,5,121,72,23,112,26.2,0.245,30,0
766,1,126,60,0,0,30.1,0.349,47,1
767,1,93,70,31,0,30.4,0.315,23,0

In [37]:
#Split in features and target variable
feature_cols = ['Pregnancies','Glucose','BloodPressure','SkinThickness','Insulin','BMI','DiabetesPedigreeFunction','Age']
X= pima[feature_cols]
y = pima.Outcome

In [39]:
y

0      1
1      0
2      1
3      0
4      1
5      0
6      1
7      0
8      1
9      1
10     0
11     1
12     0
13     1
14     1
15     1
16     1
17     1
18     0
19     1
20     0
21     0
22     1
23     1
24     1
25     1
26     1
27     0
28     0
29     0
      ..
738    0
739    1
740    1
741    0
742    0
743    1
744    0
745    0
746    1
747    0
748    1
749    1
750    1
751    0
752    0
753    1
754    1
755    1
756    0
757    1
758    0
759    1
760    0
761    1
762    0
763    0
764    0
765    0
766    1
767    0
Name: Outcome, Length: 768, dtype: int64

In [40]:
from sklearn.ensemble import BaggingClassifier
from sklearn.tree import DecisionTreeClassifier
bag_clf1 = BaggingClassifier(DecisionTreeClassifier(),n_estimators = 100,
                            max_samples= 10,
                             bootstrap=True,
                             oob_score = True)
#It trains an ensmeble of 100DecisionTree classifiers each trained with 10 training instances randomly sampled 
#from training set with replacement 
#n_jobs parameter tells scikit-learn the number of CPU cores to use for traning and predictions

In [41]:
#split the dataset into training and testing data
from sklearn.model_selection import train_test_split
X_train,X_test,y_train,y_test = train_test_split(X,y,test_size= 0.25,random_state = 0)

In [42]:
bag_clf = BaggingClassifier(DecisionTreeClassifier(),n_estimators=100,
                            bootstrap = True,
                           n_jobs = -1,oob_score = True)

In [43]:
bag_clf.fit(X_train,y_train)
bag_clf.oob_score_

0.7361111111111112

In [44]:
bag_clf1.fit(X_train,y_train)
bag_clf1.oob_score_

0.7274305555555556

In [45]:
y_pred = bag_clf.predict(X_test)
accuracy_score(y_test,y_pred)

0.8020833333333334

In [46]:
y_pred = bag_clf1.predict(X_test)
accuracy_score(y_test,y_pred)

0.71875

According to the oob evaluation,the Bagging classifier is likely achieve more accuracy
on the test

In [47]:
from sklearn.ensemble import AdaBoostClassifier
from sklearn.datasets import load_breast_cancer
import numpy as np
from sklearn.metrics import confusion_matrix
from sklearn.preprocessing import LabelEncoder

In [48]:
breast_cancer = load_breast_cancer()
X = pd.DataFrame(breast_cancer.data,columns = breast_cancer.feature_names)
y = pd.Categorical.from_codes(breast_cancer.target,breast_cancer.target_names)

In [52]:
y

[malignant, malignant, malignant, malignant, malignant, ..., malignant, malignant, malignant, malignant, benign]
Length: 569
Categories (2, object): [malignant, benign]

In [53]:
#Whenever we are working with categorical feature,we must encode it as numbers.
encoder = LabelEncoder()
binary_encoded_y = pd.Series(encoder.fit_transform(y))

In [54]:
X_train,X_test,y_train,y_test = train_test_split(X,binary_encoded_y,random_state =1)

In [55]:
classifier = AdaBoostClassifier(DecisionTreeClassifier(max_depth = 2),
                                n_estimators = 200)
classifier.fit(X_train,y_train)
#SAMME.R - Stagewise Additive Modelling using a multiclass Exponential Loss function Real

AdaBoostClassifier(algorithm='SAMME.R',
          base_estimator=DecisionTreeClassifier(class_weight=None, criterion='gini', max_depth=2,
            max_features=None, max_leaf_nodes=None,
            min_impurity_decrease=0.0, min_impurity_split=None,
            min_samples_leaf=1, min_samples_split=2,
            min_weight_fraction_leaf=0.0, presort=False, random_state=None,
            splitter='best'),
          learning_rate=1.0, n_estimators=200, random_state=None)

SAMME.R relies on class probabilities rather than the predictions and generally performs better

In [56]:
predictions = classifier.predict(X_test)

In [57]:
confusion_matrix(y_test,predictions)

array([[88,  0],
       [ 4, 51]], dtype=int64)

In [58]:
from sklearn.metrics import accuracy_score
accuracy_score(y_test,predictions)

0.972027972027972

In [59]:
#GradientBoosting
from sklearn.preprocessing import MinMaxScaler
from sklearn.ensemble import GradientBoostingClassifier

In [60]:
train_data = pd.read_csv("train.csv")
test_data = pd.read_csv("test.csv")

We may need to do some preprocessing

In [61]:
y_train = train_data["Survived"]
train_data.drop(labels ='Survived',axis = 1,inplace = True)

In [62]:
full_data = train_data.append(test_data)

In [63]:
drop_columns = ['Name','Age','SibSp','Ticket','Cabin','Parch','Embarked']
full_data.drop(labels = drop_columns,axis=1,inplace = True)

In [64]:
full_data

     PassengerId  Pclass     Sex      Fare
0              1       3    male    7.2500
1              2       1  female   71.2833
2              3       3  female    7.9250
3              4       1  female   53.1000
4              5       3    male    8.0500
5              6       3    male    8.4583
6              7       1    male   51.8625
7              8       3    male   21.0750
8              9       3  female   11.1333
9             10       2  female   30.0708
10            11       3  female   16.7000
11            12       1  female   26.5500
12            13       3    male    8.0500
13            14       3    male   31.2750
14            15       3  female    7.8542
15            16       2  female   16.0000
16            17       3    male   29.1250
17            18       2    male   13.0000
18            19       3  female   18.0000
19            20       3  female    7.2250
20            21       2    male   26.0000
21            22       2    male   13.0000
22            23       3  female    8.0292
23            24       1    male   35.5000
24            25       3  female   21.0750
25            26       3  female   31.3875
26            27       3    male    7.2250
27            28       1    male  263.0000
28            29       3  female    7.8792
29            30       3    male    7.8958
..           ...     ...     ...       ...
388         1280       3    male    7.7500
389         1281       3    male   21.0750
390         1282       1    male   93.5000
391         1283       1  female   39.4000
392         1284       3    male   20.2500
393         1285       2    male   10.5000
394         1286       3    male   22.0250
395         1287       1  female   60.0000
396         1288       3    male    7.2500
397         1289       1  female   79.2000
398         1290       3    male    7.7750
399         1291       3    male    7.7333
400         1292       1  female  164.8667
401         1293       2    male   21.0000
402         1294       1  female   59.4000
403         1295       1    male   47.1000
404         1296       1    male   27.7208
405         1297       2    male   13.8625
406         1298       2    male   10.5000
407         1299       1    male  211.5000
408         1300       3  female    7.7208
409         1301       3  female   13.7750
410         1302       3  female    7.7500
411         1303       1  female   90.0000
412         1304       3  female    7.7750
413         1305       3    male    8.0500
414         1306       1  female  108.9000
415         1307       3    male    7.2500
416         1308       3    male    8.0500
417         1309       3    male   22.3583

[1309 rows x 4 columns]

In [65]:
full_data = pd.get_dummies(full_data,columns = ["Sex"])
full_data

     PassengerId  Pclass      Fare  Sex_female  Sex_male
0              1       3    7.2500           0         1
1              2       1   71.2833           1         0
2              3       3    7.9250           1         0
3              4       1   53.1000           1         0
4              5       3    8.0500           0         1
5              6       3    8.4583           0         1
6              7       1   51.8625           0         1
7              8       3   21.0750           0         1
8              9       3   11.1333           1         0
9             10       2   30.0708           1         0
10            11       3   16.7000           1         0
11            12       1   26.5500           1         0
12            13       3    8.0500           0         1
13            14       3   31.2750           0         1
14            15       3    7.8542           1         0
15            16       2   16.0000           1         0
16            17       3   29.1250           0         1
17            18       2   13.0000           0         1
18            19       3   18.0000           1         0
19            20       3    7.2250           1         0
20            21       2   26.0000           0         1
21            22       2   13.0000           0         1
22            23       3    8.0292           1         0
23            24       1   35.5000           0         1
24            25       3   21.0750           1         0
25            26       3   31.3875           1         0
26            27       3    7.2250           0         1
27            28       1  263.0000           0         1
28            29       3    7.8792           1         0
29            30       3    7.8958           0         1
..           ...     ...       ...         ...       ...
388         1280       3    7.7500           0         1
389         1281       3   21.0750           0         1
390         1282       1   93.5000           0         1
391         1283       1   39.4000           1         0
392         1284       3   20.2500           0         1
393         1285       2   10.5000           0         1
394         1286       3   22.0250           0         1
395         1287       1   60.0000           1         0
396         1288       3    7.2500           0         1
397         1289       1   79.2000           1         0
398         1290       3    7.7750           0         1
399         1291       3    7.7333           0         1
400         1292       1  164.8667           1         0
401         1293       2   21.0000           0         1
402         1294       1   59.4000           1         0
403         1295       1   47.1000           0         1
404         1296       1   27.7208           0         1
405         1297       2   13.8625           0         1
406         1298       2   10.5000           0         1
407         1299       1  211.5000           0         1
408         1300       3    7.7208           1         0
409         1301       3   13.7750           1         0
410         1302       3    7.7500           1         0
411         1303       1   90.0000           1         0
412         1304       3    7.7750           1         0
413         1305       3    8.0500           0         1
414         1306       1  108.9000           1         0
415         1307       3    7.2500           0         1
416         1308       3    8.0500           0         1
417         1309       3   22.3583           0         1

[1309 rows x 5 columns]

In [66]:
full_data.fillna(value = 0.0,inplace = True)

In [67]:
full_data.isnull().sum()

PassengerId    0
Pclass         0
Fare           0
Sex_female     0
Sex_male       0
dtype: int64

In [68]:
#Lets split the data
X_train = full_data.values[0:891]
X_test = full_data.values[891:]

In [70]:
X_train

array([[  1.    ,   3.    ,   7.25  ,   0.    ,   1.    ],
       [  2.    ,   1.    ,  71.2833,   1.    ,   0.    ],
       [  3.    ,   3.    ,   7.925 ,   1.    ,   0.    ],
       ...,
       [889.    ,   3.    ,  23.45  ,   1.    ,   0.    ],
       [890.    ,   1.    ,  30.    ,   0.    ,   1.    ],
       [891.    ,   3.    ,   7.75  ,   0.    ,   1.    ]])

In [71]:
#We have scaled the data into training and testing sets:
scaler = MinMaxScaler()
X_train = scaler.fit_transform(X_train)
X_test = scaler.transform(X_test)

In [72]:
X_train,X_val,y_train,y_val = train_test_split(X_train,y_train,test_size = 0.3,random_state = 12)

We can try by setting different learning rates,so that we can compare the performance of the classifier's at different learning rates

In [73]:
lr_list =[0.05,0.075,0.1,0.25,0.5,0.75,1]
for learning_rate in lr_list:
    gb_clf=GradientBoostingClassifier(n_estimators=20,
                                      learning_rate = learning_rate,
                                      max_features=2)
    gb_clf.fit(X_train,y_train)
    
    print("Learning rate",learning_rate)
    print("Accuracy score (training):{0:.3f}".format(gb_clf.score(X_train,y_train)))
    print("Accuracy score (validation):{0:.3f}".format(gb_clf.score(X_val,y_val)))

Learning rate 0.05
Accuracy score (training):0.830
Accuracy score (validation):0.750
Learning rate 0.075
Accuracy score (training):0.841
Accuracy score (validation):0.784
Learning rate 0.1
Accuracy score (training):0.836
Accuracy score (validation):0.772
Learning rate 0.25
Accuracy score (training):0.875
Accuracy score (validation):0.772
Learning rate 0.5
Accuracy score (training):0.902
Accuracy score (validation):0.769
Learning rate 0.75
Accuracy score (training):0.912
Accuracy score (validation):0.750
Learning rate 1
Accuracy score (training):0.925
Accuracy score (validation):0.765

In [74]:
from sklearn.metrics import classification_report
gb_clf2 = GradientBoostingClassifier(n_estimators = 20,learning_rate = 0.5,
                                     max_features = 2,max_depth=2)
gb_clf2.fit(X_train,y_train)
predictions = gb_clf2.predict(X_val)
print("Confusion Matrix:")
print(confusion_matrix(y_val,predictions))
print("Classification Report:")
print(classification_report(y_val,predictions))

Confusion Matrix:
[[142  19]
 [ 48  59]]
Classification Report:
              precision    recall  f1-score   support

           0       0.75      0.88      0.81       161
           1       0.76      0.55      0.64       107

   micro avg       0.75      0.75      0.75       268
   macro avg       0.75      0.72      0.72       268
weighted avg       0.75      0.75      0.74       268